CREATE TABLE IF NOT EXISTS `azhiyoorpanchayath`.`house_details` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CLUSTER` VARCHAR(20) NULL DEFAULT NULL,
  `WARDNO` VARCHAR(2) NULL DEFAULT NULL,
  `HOUSE_NO` VARCHAR(20) NULL DEFAULT NULL,
  `RATIONCARD_NO` VARCHAR(20) NULL DEFAULT NULL,
  `HOUSE_OWNER_ID` INT NULL DEFAULT NULL,
  `HOUSE_NAME` VARCHAR(50) NULL DEFAULT NULL,
  `HOUSE_LAND_NAME` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
