CREATE TABLE IF NOT EXISTS `azhiyoorpanchayath`.`member_master` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RECORD_STATUS` VARCHAR(20) NULL DEFAULT NULL,
  `CREATED_DATE` DATE NULL DEFAULT NULL,
  `VERIFIED_DATE` DATE NULL DEFAULT NULL,
  `APPROVED_DATE` DATE NULL DEFAULT NULL,
  `CREATED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `VERIFIED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `APPROVED_BY` VARCHAR(20) NULL DEFAULT NULL,
  `IS_HEAD` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
